language: java
sudo: false
dist: trusty
group: edge

addons:
  sonarcloud:
    organization: trellis-ldp

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
  - rm -f  $HOME/.gradle/caches/*/fileHashes/fileHashes.bin
  - rm -f  $HOME/.gradle/caches/*/fileHashes/fileHashes.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

stages:
  - test
  - deploy

branches:
  only:
    - master
    # release tags
    - /^trellis-\d+\.\d+\.\d+$/
    # maintenance branches
    - /^trellis-\d+\.\d+\.x$/
    # long-lived branches
    - /branch-.+/

env:

jobs:
  allow_failures:
    - env: JOB=sonatype
    - env: JOB=docker

  include:
    # JDK 8
    - name: "Java 8"
      stage: test
      jdk: oraclejdk8
      env: JOB=check
      script: travis_retry ./gradlew check install jacocoRootReport coveralls sonarqube -Pitests

    # JDK 11
    - name: "Java 11"
      stage: test
      jdk: openjdk11
      env: JOB=check
      script: travis_retry ./gradlew check install -Pitests

    # deploy JDK 8 builds to Sonatype
    - name: "Publish to Sonatype"
      stage: deploy
      jdk: oraclejdk8
      env: JOB=sonatype
      if: branch = master AND type = push
      # Only automate the publication of SNAPSHOTS
      script: if [[ $(./gradlew -q getVersion) == *SNAPSHOT* ]]; then ./gradlew publish ; fi

    # deploy to Docker hub
    - name: "Publish to Docker hub"
      stage: deploy
      jdk: oraclejdk8
      if: branch = master AND type = push
      env: JOB=docker
      before_script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      script: ./gradlew dockerPush

